"""
    Swagger Music Shop

    Music shop REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cart_line_item_dto import CartLineItemDTO
globals()['CartLineItemDTO'] = CartLineItemDTO
from openapi_client.model.shopping_cart_dto import ShoppingCartDTO


class TestShoppingCartDTO(unittest.TestCase):
    """ShoppingCartDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShoppingCartDTO(self):
        """Test ShoppingCartDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShoppingCartDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
