"""
    Swagger Music Shop

    Music shop REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.invoice_line_item_dto import InvoiceLineItemDTO


class TestInvoiceLineItemDTO(unittest.TestCase):
    """InvoiceLineItemDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoiceLineItemDTO(self):
        """Test InvoiceLineItemDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvoiceLineItemDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
