"""


    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.artist_dto import ArtistDTO


class TestArtistDTO(unittest.TestCase):
    """ArtistDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArtistDTO(self):
        """Test ArtistDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArtistDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
