"""
    Swagger Music Shop

    Music shop REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.album_id import AlbumId
from openapi_client.model.song_dto import SongDTO
globals()['AlbumId'] = AlbumId
globals()['SongDTO'] = SongDTO
from openapi_client.model.album_dto import AlbumDTO


class TestAlbumDTO(unittest.TestCase):
    """AlbumDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlbumDTO(self):
        """Test AlbumDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlbumDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
