"""


    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cart_line_item_dto import CartLineItemDTO


class TestCartLineItemDTO(unittest.TestCase):
    """CartLineItemDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCartLineItemDTO(self):
        """Test CartLineItemDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CartLineItemDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
