"""


    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.album_id import AlbumId


class TestAlbumId(unittest.TestCase):
    """AlbumId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlbumId(self):
        """Test AlbumId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlbumId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
