"""


    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_to_cart(self):
        """Test case for add_to_cart

        """
        pass

    def test_buy_product(self):
        """Test case for buy_product

        """
        pass

    def test_clear_shopping_cart(self):
        """Test case for clear_shopping_cart

        """
        pass

    def test_display_shopping_cart(self):
        """Test case for display_shopping_cart

        """
        pass

    def test_find_albums_by_song_title(self):
        """Test case for find_albums_by_song_title

        """
        pass

    def test_login(self):
        """Test case for login

        """
        pass

    def test_login_web(self):
        """Test case for login_web

        """
        pass

    def test_welcome(self):
        """Test case for welcome

        """
        pass


if __name__ == '__main__':
    unittest.main()
