"""
    Swagger Music Shop

    Music shop REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_albums_to_cart(self):
        """Test case for add_albums_to_cart

        """
        pass

    def test_add_songs_from_album_to_cart(self):
        """Test case for add_songs_from_album_to_cart

        """
        pass

    def test_add_songs_to_cart(self):
        """Test case for add_songs_to_cart

        """
        pass

    def test_buy_product(self):
        """Test case for buy_product

        """
        pass

    def test_buy_products_web(self):
        """Test case for buy_products_web

        """
        pass

    def test_clear_shopping_cart(self):
        """Test case for clear_shopping_cart

        """
        pass

    def test_display_shopping_cart(self):
        """Test case for display_shopping_cart

        """
        pass

    def test_find_album_by_album_id(self):
        """Test case for find_album_by_album_id

        """
        pass

    def test_find_albums_by_song_title(self):
        """Test case for find_albums_by_song_title

        """
        pass

    def test_find_albums_by_song_title_physical(self):
        """Test case for find_albums_by_song_title_physical

        """
        pass

    def test_login(self):
        """Test case for login

        """
        pass

    def test_login_web(self):
        """Test case for login_web

        """
        pass

    def test_remove_line_item_from_cart(self):
        """Test case for remove_line_item_from_cart

        """
        pass

    def test_welcome(self):
        """Test case for welcome

        """
        pass


if __name__ == '__main__':
    unittest.main()
