"""
    Swagger Music Shop

    Music shop REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.album_dto import AlbumDTO
from openapi_client.model.artist_dto import ArtistDTO
globals()['AlbumDTO'] = AlbumDTO
globals()['ArtistDTO'] = ArtistDTO
from openapi_client.model.song_dto import SongDTO


class TestSongDTO(unittest.TestCase):
    """SongDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSongDTO(self):
        """Test SongDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SongDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
